wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    code_path: code/Train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1647195931
    t:
      1:
      - 1
      - 41
      2:
      - 1
      - 41
      4: 3.9.7
      5: 0.12.11
      8:
      - 5
amp:
  desc: null
  value: false
batch_size:
  desc: null
  value: 20
epochs:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.0001
save_checkpoint:
  desc: null
  value: true
